version: '2'

services:
  fpm:
    build: docker/php-fpm
    ports:
      - 9002:9002
    volumes:
      - ../app/:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/php:/var/log/php

  composer:
    build: docker/php-composer
    volumes:
      - ../app/:/app

  nginx:
    image: nginx:stable-alpine
    links:
      - php-fpm:fpm
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/vhost.conf:/tmp/vhost.conf
      - ../app/:/app
      - ../frontend/:/frontend
      - ./logs/nginx/:/log
    environment:
      - FRONTEND_URL=galamart-is.ru
      - BACKEND_URL=api.galamart-is.ru
    command: /bin/sh -c "envsubst '$$FRONTEND_URL \n $$BACKEND_URL ' < /tmp/vhost.conf >/etc/nginx/conf.d/vhost.conf && nginx -g 'daemon off;'"

  db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - 5432:5432
    environment:
      - DEBUG=false

      - DB_USER=dev
      - DB_PASS=dev
      - DB_NAME=gis
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672

  memcached1:
    image: memcached:alpine
    ports:
      - 11211:11211

  memcached2:
    image: memcached:alpine
    ports:
      - 11212:11212